name: CI

on:
  push:
    branches: [ main, develop, feat/** ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SENTRY_DSN: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run type-check
      - name: Unit tests
        run: npm test -- --ci

  expo-preview:
    if: ${{ secrets.EXPO_TOKEN != '' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Expo login
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: EAS build preview (Android)
        run: npx eas build --platform android --profile preview --non-interactive
